version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/00-mongo-init.sh
