version: "3"
services:
  db-starter:
    container_name: db-starter
    build:
      context: .
      dockerfile: db-starter.Dockerfile
      cache_from:
        - debian:stable-slim
      args:
        MONGOSH_VERSION: "1.2.2"
    env_file:
      - .env
    depends_on:
      - mongodb-primary
      - mongodb-replica
  mongodb-primary:
    container_name: mongodb-primary
    image: mongo:latest
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /docker-entrypoint-initdb.d/dev.key
        chown 999:999 /docker-entrypoint-initdb.d/dev.key
        exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --replSet mongo-cluster --keyFile /docker-entrypoint-initdb.d/dev.key
    env_file:
      - mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/00-mongo-init.sh
      - ./docker-entrypoint-initdb.d/dev.key:/docker-entrypoint-initdb.d/dev.key
  mongodb-replica:
    container_name: mongodb-replica
    image: mongo:latest
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /docker-entrypoint-initdb.d/dev.key
        chown 999:999 /docker-entrypoint-initdb.d/dev.key
        exec docker-entrypoint.sh $$@
    command: mongod --replSet mongo-cluster --keyFile /docker-entrypoint-initdb.d/dev.key
    depends_on:
      - mongodb-primary
    env_file:
      - mongodb.env
    ports:
      - 27018:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/00-mongo-init.sh
      - ./docker-entrypoint-initdb.d/dev.key:/docker-entrypoint-initdb.d/dev.key
