version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:alpine
    entrypoint:
      - bash
      - -c
      - |
        if [[ -f .firstboot ]]; then node .; fi
        npm run prisma:up
        npm run build
        touch .firstboot
        node .
    command: node .
    env_file:
      - production.env
    depends_on:
      - db-starter
      - mongodb-primary
      - mongodb-replica
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-post-init.js:/docker-entrypoint-initdb.d/mongo-post-init.js
  db-starter:
    container_name: db-starter
    build:
      context: .
      dockerfile: db-starter.Dockerfile
      cache_from:
        - debian:stable-slim
      args:
        MONGOSH_VERSION: "1.2.2"
    env_file:
      - production.env
    depends_on:
      - mongodb-primary
      - mongodb-replica
  mongodb-primary:
    container_name: mongodb-primary
    image: mongo:latest
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /docker-entrypoint-initdb.d/prod.key
        chown 999:999 /docker-entrypoint-initdb.d/prod.key
        exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --replSet mongo-cluster --keyFile /docker-entrypoint-initdb.d/prod.key
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/00-mongo-init.sh
      - ./docker-entrypoint-initdb.d/mongo-post-init.js:/docker-entrypoint-initdb.d/mongo-post-init.js
      - ./docker-entrypoint-initdb.d/prod.key:/docker-entrypoint-initdb.d/prod.key
  mongodb-replica:
    container_name: mongodb-replica
    image: mongo:latest
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /docker-entrypoint-initdb.d/prod.key
        chown 999:999 /docker-entrypoint-initdb.d/prod.key
        exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --replSet mongo-cluster --keyFile /docker-entrypoint-initdb.d/prod.key
    restart: always
    depends_on:
      - mongodb-primary
    env_file:
      - mongodb.env
    ports:
      - 27018:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/00-mongo-init.sh
      - ./docker-entrypoint-initdb.d/mongo-post-init.js:/docker-entrypoint-initdb.d/mongo-post-init.js
      - ./docker-entrypoint-initdb.d/prod.key:/docker-entrypoint-initdb.d/prod.key
